spring.application.name=cloud-performance-api

spring.jackson.serialization.indent-output=true

spring.servlet.multipart.max-file-size=500MB
spring.servlet.multipart.max-request-size=500MB

spring.datasource.url=jdbc:h2:file:./data/performance-db
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false